import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // 1. 产品指南 (01 平台说明、02 快速开始、03 用户操作手册)
  productSidebar: [
    {
      type: 'category',
      label: '01 平台说明',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: '01-platform'}],
    },
    {
      type: 'category',
      label: '02 快速开始',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: '02-quick-start'}],
    },
    {
      type: 'category',
      label: '03 用户操作手册',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: '03-user-guide'}],
    },
  ],

  // 2. 算法与场景 (04 业务场景方案、05 算法与算子说明)
  algorithmSidebar: [
    {
      type: 'category',
      label: '04 业务场景方案',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: '04-scenarios'}],
    },
    {
      type: 'category',
      label: '05 算法与算子说明',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: '05-algorithms'}],
    },
  ],

  // 3. 开发者中心 (06 API 与二次开发)
  devSidebar: [
    {
      type: 'category',
      label: '06 API 与开发集成',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: '06-development'}],
    },
  ],

  // 4. 部署与运维 (07 部署与运维、08 测试验收与交付)
  opsSidebar: [
    {
      type: 'category',
      label: '07 部署与运维',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: '07-operations'}],
    },
    {
      type: 'category',
      label: '08 测试验收与交付',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: '08-acceptance'}],
    },
  ],
};

export default sidebars;
